default_context:
  project_name: 'store-monitor'
  project_slug: 'store-monitor'
  domain_main: 'store-monitor.com'
  domain_staging: 'stag.store-monitor.com'
  docker_swarm_stack_name_main: 'store-monitor-com'
  docker_swarm_stack_name_staging: 'stag-store-monitor-com'
  secret_key: 'changethis'
  first_superuser: 'admin@store-monitor.com'
  first_superuser_password: 'changethis'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.store-monitor.com", "https://stag.store-monitor.com", "https://store-monitor.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@store-monitor.com'
  postgres_password: 'changethis'
  pgadmin_default_user: 'admin@store-monitor.com'
  pgadmin_default_user_password: 'changethis'
  traefik_constraint_tag: 'store-monitor.com'
  traefik_constraint_tag_staging: 'stag.store-monitor.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:changethis'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  _template: ./
