"""created store tables

Revision ID: 9064432d3577
Revises: 
Create Date: 2023-08-09 21:53:03.304511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9064432d3577'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store_hours',
    sa.Column('store_id', sa.BigInteger(), nullable=True),
    sa.Column('day', sa.Integer(), nullable=True),
    sa.Column('start_time_local', sa.Time(), server_default='00:00:00', nullable=False),
    sa.Column('end_time_local', sa.Time(), server_default='23:59:59', nullable=False)
    )
    op.create_index(op.f('ix_store_hours_store_id'), 'store_hours', ['store_id'], unique=False)
    op.create_table('store_status',
    sa.Column('store_id', sa.BigInteger(), nullable=True),
    sa.Column('timestamp_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', name='statusenum'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True)
    )
    op.create_index(op.f('ix_store_status_store_id'), 'store_status', ['store_id'], unique=False)
    op.create_table('store_tz',
    sa.Column('store_id', sa.BigInteger(), nullable=False),
    sa.Column('timezone_str', sa.VARCHAR(length=32), server_default='America/Chicago', nullable=True),
    sa.PrimaryKeyConstraint('store_id')
    )
    op.create_index(op.f('ix_store_tz_store_id'), 'store_tz', ['store_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_store_tz_store_id'), table_name='store_tz')
    op.drop_table('store_tz')
    op.drop_index(op.f('ix_store_status_store_id'), table_name='store_status')
    op.drop_table('store_status')
    op.drop_index(op.f('ix_store_hours_store_id'), table_name='store_hours')
    op.drop_table('store_hours')
    # ### end Alembic commands ###
