"""created report table

Revision ID: bcbee78fa182
Revises: 9064432d3577
Create Date: 2023-08-12 18:44:49.082672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bcbee78fa182'
down_revision: Union[str, None] = '9064432d3577'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report',
    sa.Column('report_id', postgresql.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'complete', 'failed', name='reportstatusenum'), nullable=False),
    sa.Column('download_link', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_index(op.f('ix_report_report_id'), 'report', ['report_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_report_report_id'), table_name='report')
    op.drop_table('report')
    # ### end Alembic commands ###
